import Country from '#models/country'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  static environment = ['development', 'test', 'production']

  async run() {
    const uniqueKey = `isoCode`

    await Country.updateOrCreateMany(uniqueKey, [
      { isoCode: `AF`, name: `Afghanistan`, nationality: `Afghan`, phoneCode: `+93` },
      { isoCode: `AX`, name: `Aland Islands`, nationality: `Alandish`, phoneCode: `+358` },
      { isoCode: `AL`, name: `Albania`, nationality: `Albanian`, phoneCode: `+355` },
      { isoCode: `DZ`, name: `Algeria`, nationality: `Algerian`, phoneCode: `+213` },
      { isoCode: `AS`, name: `American Samoa`, nationality: `American Samoan`, phoneCode: `+1684` },
      { isoCode: `AD`, name: `AndorrA`, nationality: `Andorran`, phoneCode: `+376` },
      { isoCode: `AO`, name: `Angola`, nationality: `Angolan`, phoneCode: `+244` },
      { isoCode: `AI`, name: `Anguilla`, nationality: `Anguillan`, phoneCode: `+1264` },
      { isoCode: `AQ`, name: `Antarctica`, nationality: `Antarctic`, phoneCode: `+672` },
      {
        isoCode: `AG`,
        name: `Antigua and Barbuda`,
        nationality: `Antiguan or Barbudan`,
        phoneCode: `+1268`,
      },
      { isoCode: `AR`, name: `Argentina`, nationality: `Argentine`, phoneCode: `+54` },
      { isoCode: `AM`, name: `Armenia`, nationality: `Armenian`, phoneCode: `+374` },
      { isoCode: `AW`, name: `Aruba`, nationality: `Aruban`, phoneCode: `+297` },
      { isoCode: `AU`, name: `Australia`, nationality: `Australian`, phoneCode: `+61` },
      { isoCode: `AT`, name: `Austria`, nationality: `Austrian`, phoneCode: `+43` },
      { isoCode: `AZ`, name: `Azerbaijan`, nationality: `Azerbaijani`, phoneCode: `+994` },
      { isoCode: `BS`, name: `Bahamas`, nationality: `Bahamian`, phoneCode: `+1242` },
      { isoCode: `BH`, name: `Bahrain`, nationality: `Bahraini`, phoneCode: `+973` },
      { isoCode: `BD`, name: `Bangladesh`, nationality: `Bangladeshi`, phoneCode: `+880` },
      { isoCode: `BB`, name: `Barbados`, nationality: `Barbadian`, phoneCode: `+1246` },
      { isoCode: `BY`, name: `Belarus`, nationality: `Belarusian`, phoneCode: `+375` },
      { isoCode: `BE`, name: `Belgium`, nationality: `Belgian`, phoneCode: `+32` },
      { isoCode: `BZ`, name: `Belize`, nationality: `Belizean`, phoneCode: `+501` },
      { isoCode: `BJ`, name: `Benin`, nationality: `Beninese`, phoneCode: `+229` },
      { isoCode: `BM`, name: `Bermuda`, nationality: `Bermudian`, phoneCode: `+1441` },
      { isoCode: `BT`, name: `Bhutan`, nationality: `Bhutanese`, phoneCode: `+975` },
      { isoCode: `BO`, name: `Bolivia`, nationality: `Bolivian`, phoneCode: `+591` },
      {
        isoCode: `BA`,
        name: `Bosnia and Herzegovina`,
        nationality: `Bosnian or Herzegovinian`,
        phoneCode: `+387`,
      },
      { isoCode: `BW`, name: `Botswana`, nationality: `Botswanan`, phoneCode: `+267` },
      { isoCode: `BV`, name: `Bouvet Island`, nationality: `Bouvet Islander`, phoneCode: `+47` },
      { isoCode: `BR`, name: `Brazil`, nationality: `Brazilian`, phoneCode: `+55` },
      {
        isoCode: `IO`,
        name: `British Indian Ocean Territory`,
        nationality: `British Indian Ocean Territory Citizen`,
        phoneCode: `+246`,
      },
      { isoCode: `BN`, name: `Brunei Darussalam`, nationality: `Bruneian`, phoneCode: `+673` },
      { isoCode: `BG`, name: `Bulgaria`, nationality: `Bulgarian`, phoneCode: `+359` },
      { isoCode: `BF`, name: `Burkina Faso`, nationality: `Burkinabe`, phoneCode: `+226` },
      { isoCode: `BI`, name: `Burundi`, nationality: `Burundian`, phoneCode: `+257` },
      { isoCode: `KH`, name: `Cambodia`, nationality: `Cambodian`, phoneCode: `+855` },
      { isoCode: `CM`, name: `Cameroon`, nationality: `Cameroonian`, phoneCode: `+237` },
      { isoCode: `CA`, name: `Canada`, nationality: `Canadian`, phoneCode: `+1` },
      { isoCode: `CV`, name: `Cape Verde`, nationality: `Cape Verdean`, phoneCode: `+238` },
      { isoCode: `KY`, name: `Cayman Islands`, nationality: `Caymanian`, phoneCode: `+1345` },
      {
        isoCode: `CF`,
        name: `Central African Republic`,
        nationality: `Central African`,
        phoneCode: `+236`,
      },
      { isoCode: `TD`, name: `Chad`, nationality: `Chadian`, phoneCode: `+235` },
      { isoCode: `CL`, name: `Chile`, nationality: `Chilean`, phoneCode: `+56` },
      { isoCode: `CN`, name: `China`, nationality: `Chinese`, phoneCode: `+86` },
      {
        isoCode: `CX`,
        name: `Christmas Island`,
        nationality: `Christmas Islander`,
        phoneCode: `+61`,
      },
      {
        isoCode: `CC`,
        name: `Cocos (Keeling) Islands`,
        nationality: `Cocos Islander`,
        phoneCode: `+61`,
      },
      { isoCode: `CO`, name: `Colombia`, nationality: `Colombian`, phoneCode: `+57` },
      { isoCode: `KM`, name: `Comoros`, nationality: `Comoran`, phoneCode: `+269` },
      { isoCode: `CG`, name: `Congo`, nationality: `Congolese`, phoneCode: `+242` },
      {
        isoCode: `CD`,
        name: `Congo, The Democratic Republic of the`,
        nationality: `Congolese`,
        phoneCode: `+243`,
      },
      { isoCode: `CK`, name: `Cook Islands`, nationality: `Cook Islander`, phoneCode: `+682` },
      { isoCode: `CR`, name: `Costa Rica`, nationality: `Costa Rican`, phoneCode: `+506` },
      { isoCode: `CI`, name: 'Cote D`Ivoire', nationality: `Ivorian`, phoneCode: `+225` },
      { isoCode: `HR`, name: `Croatia`, nationality: `Croatian`, phoneCode: `+385` },
      { isoCode: `CU`, name: `Cuba`, nationality: `Cuban`, phoneCode: `+53` },
      { isoCode: `CY`, name: `Cyprus`, nationality: `Cypriot`, phoneCode: `+357` },
      { isoCode: `CZ`, name: `Czech Republic`, nationality: `Czech`, phoneCode: `+420` },
      { isoCode: `DK`, name: `Denmark`, nationality: `Danish`, phoneCode: `+45` },
      { isoCode: `DJ`, name: `Djibouti`, nationality: `Djiboutian`, phoneCode: `+253` },
      { isoCode: `DM`, name: `Dominica`, nationality: `Dominican`, phoneCode: `+1767` },
      { isoCode: `DO`, name: `Dominican Republic`, nationality: `Dominican`, phoneCode: `+1809` },
      { isoCode: `EC`, name: `Ecuador`, nationality: `Ecuadorian`, phoneCode: `+593` },
      { isoCode: `EG`, name: `Egypt`, nationality: `Egyptian`, phoneCode: `+20` },
      { isoCode: `SV`, name: `El Salvador`, nationality: `Salvadoran`, phoneCode: `+503` },
      {
        isoCode: `GQ`,
        name: `Equatorial Guinea`,
        nationality: `Equatorial Guinean`,
        phoneCode: `+240`,
      },
      { isoCode: `ER`, name: `Eritrea`, nationality: `Eritrean`, phoneCode: `+291` },
      { isoCode: `EE`, name: `Estonia`, nationality: `Estonian`, phoneCode: `+372` },
      { isoCode: `ET`, name: `Ethiopia`, nationality: `Ethiopian`, phoneCode: `+251` },
      {
        isoCode: `FK`,
        name: `Falkland Islands (Malvinas)`,
        nationality: `Falkland Islander`,
        phoneCode: `+500`,
      },
      { isoCode: `FO`, name: `Faroe Islands`, nationality: `Faroese`, phoneCode: `+298` },
      { isoCode: `FJ`, name: `Fiji`, nationality: `Fijian`, phoneCode: `+679` },
      { isoCode: `FI`, name: `Finland`, nationality: `Finnish`, phoneCode: `+358` },
      { isoCode: `FR`, name: `France`, nationality: `French`, phoneCode: `+33` },
      { isoCode: `GF`, name: `French Guiana`, nationality: `French Guianese`, phoneCode: `+594` },
      {
        isoCode: `PF`,
        name: `French Polynesia`,
        nationality: `French Polynesian`,
        phoneCode: `+689`,
      },
      {
        isoCode: `TF`,
        name: `French Southern Territories`,
        nationality: `French Southern Territories Citizen`,
        phoneCode: `+33`,
      },
      { isoCode: `GA`, name: `Gabon`, nationality: `Gabonese`, phoneCode: `+241` },
      { isoCode: `GM`, name: `Gambia`, nationality: `Gambian`, phoneCode: `+220` },
      { isoCode: `GE`, name: `Georgia`, nationality: `Georgian`, phoneCode: `+995` },
      { isoCode: `DE`, name: `Germany`, nationality: `German`, phoneCode: `+49` },
      { isoCode: `GH`, name: `Ghana`, nationality: `Ghanaian`, phoneCode: `+233` },
      { isoCode: `GI`, name: `Gibraltar`, nationality: `Gibraltarian`, phoneCode: `+350` },
      { isoCode: `GR`, name: `Greece`, nationality: `Greek`, phoneCode: `+30` },
      { isoCode: `GL`, name: `Greenland`, nationality: `Greenlandic`, phoneCode: `+299` },
      { isoCode: `GD`, name: `Grenada`, nationality: `Grenadian`, phoneCode: `+1473` },
      { isoCode: `GP`, name: `Guadeloupe`, nationality: `Guadeloupean`, phoneCode: `+590` },
      { isoCode: `GU`, name: `Guam`, nationality: `Guamanian`, phoneCode: `+1671` },
      { isoCode: `GT`, name: `Guatemala`, nationality: `Guatemalan`, phoneCode: `+502` },
      { isoCode: `GG`, name: `Guernsey`, nationality: `Guernsey Citizen`, phoneCode: `+44` },
      { isoCode: `GN`, name: `Guinea`, nationality: `Guinean`, phoneCode: `+224` },
      { isoCode: `GW`, name: `Guinea-Bissau`, nationality: `Guinea-Bissauan`, phoneCode: `+245` },
      { isoCode: `GY`, name: `Guyana`, nationality: `Guyanese`, phoneCode: `+592` },
      { isoCode: `HT`, name: `Haiti`, nationality: `Haitian`, phoneCode: `+509` },
      {
        isoCode: `HM`,
        name: `Heard Island and Mcdonald Islands`,
        nationality: `Heard and McDonald Islander`,
        phoneCode: `+672`,
      },
      {
        isoCode: `VA`,
        name: `Holy See (Vatican City State)`,
        nationality: `Vatican`,
        phoneCode: `+379`,
      },
      { isoCode: `HN`, name: `Honduras`, nationality: `Honduran`, phoneCode: `+504` },
      { isoCode: `HK`, name: `Hong Kong`, nationality: `Hong Kong Citizen`, phoneCode: `+852` },
      { isoCode: `HU`, name: `Hungary`, nationality: `Hungarian`, phoneCode: `+36` },
      { isoCode: `IS`, name: `Iceland`, nationality: `Icelandic`, phoneCode: `+354` },
      { isoCode: `IN`, name: `India`, nationality: `Indian`, phoneCode: `+91` },
      { isoCode: `ID`, name: `Indonesia`, nationality: `Indonesian`, phoneCode: `+62` },
      {
        isoCode: `IR`,
        name: `Iran, Islamic Republic Of`,
        nationality: `Iranian`,
        phoneCode: `+98`,
      },
      { isoCode: `IQ`, name: `Iraq`, nationality: `Iraqi`, phoneCode: `+964` },
      { isoCode: `IE`, name: `Ireland`, nationality: `Irish`, phoneCode: `+353` },
      { isoCode: `IM`, name: `Isle of Man`, nationality: `Manx`, phoneCode: `+44` },
      { isoCode: `IL`, name: `Israel`, nationality: `Israeli`, phoneCode: `+972` },
      { isoCode: `IT`, name: `Italy`, nationality: `Italian`, phoneCode: `+39` },
      { isoCode: `JM`, name: `Jamaica`, nationality: `Jamaican`, phoneCode: `+1876` },
      { isoCode: `JP`, name: `Japan`, nationality: `Japanese`, phoneCode: `+81` },
      { isoCode: `JE`, name: `Jersey`, nationality: `Jersey Citizen`, phoneCode: `+44` },
      { isoCode: `JO`, name: `Jordan`, nationality: `Jordanian`, phoneCode: `+962` },
      { isoCode: `KZ`, name: `Kazakhstan`, nationality: `Kazakhstani`, phoneCode: `+7` },
      { isoCode: `KE`, name: `Kenya`, nationality: `Kenyan`, phoneCode: `+254` },
      { isoCode: `KI`, name: `Kiribati`, nationality: `I-Kiribati`, phoneCode: `+686` },
      {
        isoCode: `KP`,
        name: 'Korea, Democratic People`S Republic of',
        nationality: `North Korean`,
        phoneCode: `+850`,
      },
      { isoCode: `KR`, name: `Korea, Republic of`, nationality: `South Korean`, phoneCode: `+82` },
      { isoCode: `KW`, name: `Kuwait`, nationality: `Kuwaiti`, phoneCode: `+965` },
      { isoCode: `KG`, name: `Kyrgyzstan`, nationality: `Kyrgyzstani`, phoneCode: `+996` },
      {
        isoCode: `LA`,
        name: 'Lao People`S Democratic Republic',
        nationality: `Laotian`,
        phoneCode: `+856`,
      },
      { isoCode: `LV`, name: `Latvia`, nationality: `Latvian`, phoneCode: `+371` },
      { isoCode: `LB`, name: `Lebanon`, nationality: `Lebanese`, phoneCode: `+961` },
      { isoCode: `LS`, name: `Lesotho`, nationality: `Lesothan`, phoneCode: `+266` },
      { isoCode: `LR`, name: `Liberia`, nationality: `Liberian`, phoneCode: `+231` },
      { isoCode: `LY`, name: `Libyan Arab Jamahiriya`, nationality: `Libyan`, phoneCode: `+218` },
      { isoCode: `LI`, name: `Liechtenstein`, nationality: `Liechtensteiner`, phoneCode: `+423` },
      { isoCode: `LT`, name: `Lithuania`, nationality: `Lithuanian`, phoneCode: `+370` },
      { isoCode: `LU`, name: `Luxembourg`, nationality: `Luxembourgish`, phoneCode: `+352` },
      { isoCode: `MO`, name: `Macao`, nationality: `Macanese`, phoneCode: `+853` },
      {
        isoCode: `MK`,
        name: `Macedonia, The Former Yugoslav Republic of`,
        nationality: `Macedonian`,
        phoneCode: `+389`,
      },
      { isoCode: `MG`, name: `Madagascar`, nationality: `Malagasy`, phoneCode: `+261` },
      { isoCode: `MW`, name: `Malawi`, nationality: `Malawian`, phoneCode: `+265` },
      { isoCode: `MY`, name: `Malaysia`, nationality: `Malaysian`, phoneCode: `+60` },
      { isoCode: `MV`, name: `Maldives`, nationality: `Maldivian`, phoneCode: `+960` },
      { isoCode: `ML`, name: `Mali`, nationality: `Malian`, phoneCode: `+223` },
      { isoCode: `MT`, name: `Malta`, nationality: `Maltese`, phoneCode: `+356` },
      { isoCode: `MH`, name: `Marshall Islands`, nationality: `Marshallese`, phoneCode: `+692` },
      { isoCode: `MQ`, name: `Martinique`, nationality: `Martinican`, phoneCode: `+596` },
      { isoCode: `MR`, name: `Mauritania`, nationality: `Mauritanian`, phoneCode: `+222` },
      { isoCode: `MU`, name: `Mauritius`, nationality: `Mauritian`, phoneCode: `+230` },
      { isoCode: `YT`, name: `Mayotte`, nationality: `Mahoran`, phoneCode: `+262` },
      { isoCode: `MX`, name: `Mexico`, nationality: `Mexican`, phoneCode: `+52` },
      {
        isoCode: `FM`,
        name: `Micronesia, Federated States of`,
        nationality: `Micronesian`,
        phoneCode: `+691`,
      },
      { isoCode: `MD`, name: `Moldova, Republic of`, nationality: `Moldovan`, phoneCode: `+373` },
      { isoCode: `MC`, name: `Monaco`, nationality: `Monacan`, phoneCode: `+377` },
      { isoCode: `MN`, name: `Mongolia`, nationality: `Mongolian`, phoneCode: `+976` },
      { isoCode: `MS`, name: `Montserrat`, nationality: `Montserratian`, phoneCode: `+1664` },
      { isoCode: `MA`, name: `Morocco`, nationality: `Moroccan`, phoneCode: `+212` },
      { isoCode: `MZ`, name: `Mozambique`, nationality: `Mozambican`, phoneCode: `+258` },
      { isoCode: `MM`, name: `Myanmar`, nationality: `Burmese`, phoneCode: `+95` },
      { isoCode: `NA`, name: `Namibia`, nationality: `Namibian`, phoneCode: `+264` },
      { isoCode: `NR`, name: `Nauru`, nationality: `Nauruan`, phoneCode: `+674` },
      { isoCode: `NP`, name: `Nepal`, nationality: `Nepalese`, phoneCode: `+977` },
      { isoCode: `NL`, name: `Netherlands`, nationality: `Dutch`, phoneCode: `+31` },
      {
        isoCode: `AN`,
        name: `Netherlands Antilles`,
        nationality: `Netherlands Antillean`,
        phoneCode: `+599`,
      },
      { isoCode: `NC`, name: `New Caledonia`, nationality: `New Caledonian`, phoneCode: `+687` },
      { isoCode: `NZ`, name: `New Zealand`, nationality: `New Zealand Citizen`, phoneCode: `+64` },
      { isoCode: `NI`, name: `Nicaragua`, nationality: `Nicaraguan`, phoneCode: `+505` },
      { isoCode: `NE`, name: `Niger`, nationality: `Nigerien`, phoneCode: `+227` },
      { isoCode: `NG`, name: `Nigeria`, nationality: `Nigerian`, phoneCode: `+234` },
      { isoCode: `NU`, name: `Niue`, nationality: `Niuean`, phoneCode: `+683` },
      { isoCode: `NF`, name: `Norfolk Island`, nationality: `Norfolk Islander`, phoneCode: `+672` },
      {
        isoCode: `MP`,
        name: `Northern Mariana Islands`,
        nationality: `Northern Mariana Islander`,
        phoneCode: `+1670`,
      },
      { isoCode: `NO`, name: `Norway`, nationality: `Norwegian`, phoneCode: `+47` },
      { isoCode: `OM`, name: `Oman`, nationality: `Omani`, phoneCode: `+968` },
      { isoCode: `PK`, name: `Pakistan`, nationality: `Pakistani`, phoneCode: `+92` },
      { isoCode: `PW`, name: `Palau`, nationality: `Palauan`, phoneCode: `+680` },
      {
        isoCode: `PS`,
        name: `Palestinian Territory, Occupied`,
        nationality: `Palestinian`,
        phoneCode: `+970`,
      },
      { isoCode: `PA`, name: `Panama`, nationality: `Panamanian`, phoneCode: `+507` },
      {
        isoCode: `PG`,
        name: `Papua New Guinea`,
        nationality: `Papua New Guinean`,
        phoneCode: `+675`,
      },
      { isoCode: `PY`, name: `Paraguay`, nationality: `Paraguayan`, phoneCode: `+595` },
      { isoCode: `PE`, name: `Peru`, nationality: `Peruvian`, phoneCode: `+51` },
      { isoCode: `PH`, name: `Philippines`, nationality: `Filipino`, phoneCode: `+63` },
      { isoCode: `PN`, name: `Pitcairn`, nationality: `Pitcairn Islander`, phoneCode: `+64` },
      { isoCode: `PL`, name: `Poland`, nationality: `Polish`, phoneCode: `+48` },
      { isoCode: `PT`, name: `Portugal`, nationality: `Portuguese`, phoneCode: `+351` },
      { isoCode: `PR`, name: `Puerto Rico`, nationality: `Puerto Rican`, phoneCode: `+1787` },
      { isoCode: `QA`, name: `Qatar`, nationality: `Qatari`, phoneCode: `+974` },
      { isoCode: `RE`, name: `Reunion`, nationality: `Reunionese`, phoneCode: `+262` },
      { isoCode: `RO`, name: `Romania`, nationality: `Romanian`, phoneCode: `+40` },
      { isoCode: `RU`, name: `Russian Federation`, nationality: `Russian`, phoneCode: `+7` },
      { isoCode: `RW`, name: `Rwanda`, nationality: `Rwandese`, phoneCode: `+250` },
      { isoCode: `SH`, name: `Saint Helena`, nationality: `Saint Helenian`, phoneCode: `+290` },
      {
        isoCode: `KN`,
        name: `Saint Kitts and Nevis`,
        nationality: `Kittitian or Nevisian`,
        phoneCode: `+1869`,
      },
      { isoCode: `LC`, name: `Saint Lucia`, nationality: `Saint Lucian`, phoneCode: `+1758` },
      {
        isoCode: `PM`,
        name: `Saint Pierre and Miquelon`,
        nationality: `Saint-Pierrais or Miquelonnais`,
        phoneCode: `+508`,
      },
      {
        isoCode: `VC`,
        name: `Saint Vincent and the Grenadines`,
        nationality: `Saint Vincentian or Grenadian`,
        phoneCode: `+1784`,
      },
      { isoCode: `WS`, name: `Samoa`, nationality: `Samoan`, phoneCode: `+685` },
      { isoCode: `SM`, name: `San Marino`, nationality: `Sammarinese`, phoneCode: `+378` },
      {
        isoCode: `ST`,
        name: `Sao Tome and Principe`,
        nationality: `Sao Tomean`,
        phoneCode: `+239`,
      },
      { isoCode: `SA`, name: `Saudi Arabia`, nationality: `Saudi Arabian`, phoneCode: `+966` },
      { isoCode: `SN`, name: `Senegal`, nationality: `Senegalese`, phoneCode: `+221` },
      {
        isoCode: `CS`,
        name: `Serbia and Montenegro`,
        nationality: `Serbian or Montenegrin`,
        phoneCode: `+381`,
      },
      { isoCode: `SC`, name: `Seychelles`, nationality: `Seychellois`, phoneCode: `+248` },
      { isoCode: `SL`, name: `Sierra Leone`, nationality: `Sierra Leonean`, phoneCode: `+232` },
      { isoCode: `SG`, name: `Singapore`, nationality: `Singaporean`, phoneCode: `+65` },
      { isoCode: `SK`, name: `Slovakia`, nationality: `Slovak`, phoneCode: `+421` },
      { isoCode: `SI`, name: `Slovenia`, nationality: `Slovenian`, phoneCode: `+386` },
      {
        isoCode: `SB`,
        name: `Solomon Islands`,
        nationality: `Solomon Islander`,
        phoneCode: `+677`,
      },
      { isoCode: `SO`, name: `Somalia`, nationality: `Somali`, phoneCode: `+252` },
      { isoCode: `ZA`, name: `South Africa`, nationality: `South African`, phoneCode: `+27` },
      {
        isoCode: `GS`,
        name: `South Georgia and the South Sandwich Islands`,
        nationality: `South Georgia and the South Sandwich Islander`,
        phoneCode: `+500`,
      },
      { isoCode: `ES`, name: `Spain`, nationality: `Spanish`, phoneCode: `+34` },
      { isoCode: `LK`, name: `Sri Lanka`, nationality: `Sri Lankan`, phoneCode: `+94` },
      { isoCode: `SD`, name: `Sudan`, nationality: `Sudanese`, phoneCode: `+249` },
      { isoCode: `SR`, name: `Suriname`, nationality: `Surinamese`, phoneCode: `+597` },
      {
        isoCode: `SJ`,
        name: `Svalbard and Jan Mayen`,
        nationality: `Svalbard and Jan Mayen Citizen`,
        phoneCode: `+47`,
      },
      { isoCode: `SZ`, name: `Swaziland`, nationality: `Swazi`, phoneCode: `+268` },
      { isoCode: `SE`, name: `Sweden`, nationality: `Swedish`, phoneCode: `+46` },
      { isoCode: `CH`, name: `Switzerland`, nationality: `Swiss`, phoneCode: `+41` },
      { isoCode: `SY`, name: `Syrian Arab Republic`, nationality: `Syrian`, phoneCode: `+963` },
      {
        isoCode: `TW`,
        name: `Taiwan, Province of China`,
        nationality: `Taiwanese`,
        phoneCode: `+886`,
      },
      { isoCode: `TJ`, name: `Tajikistan`, nationality: `Tajikistani`, phoneCode: `+992` },
      {
        isoCode: `TZ`,
        name: `Tanzania, United Republic of`,
        nationality: `Tanzanian`,
        phoneCode: `+255`,
      },
      { isoCode: `TH`, name: `Thailand`, nationality: `Thai`, phoneCode: `+66` },
      { isoCode: `TL`, name: `Timor-Leste`, nationality: `Timorese`, phoneCode: `+670` },
      { isoCode: `TG`, name: `Togo`, nationality: `Togolese`, phoneCode: `+228` },
      { isoCode: `TK`, name: `Tokelau`, nationality: `Tokelauan`, phoneCode: `+690` },
      { isoCode: `TO`, name: `Tonga`, nationality: `Tongan`, phoneCode: `+676` },
      {
        isoCode: `TT`,
        name: `Trinidad and Tobago`,
        nationality: `Trinidadian or Tobagonian`,
        phoneCode: `+1868`,
      },
      { isoCode: `TN`, name: `Tunisia`, nationality: `Tunisian`, phoneCode: `+216` },
      { isoCode: `TR`, name: `Turkey`, nationality: `Turkish`, phoneCode: `+90` },
      { isoCode: `TM`, name: `Turkmenistan`, nationality: `Turkmen`, phoneCode: `+993` },
      {
        isoCode: `TC`,
        name: `Turks and Caicos Islands`,
        nationality: `Turks and Caicos Islander`,
        phoneCode: `+1649`,
      },
      { isoCode: `TV`, name: `Tuvalu`, nationality: `Tuvaluan`, phoneCode: `+688` },
      { isoCode: `UG`, name: `Uganda`, nationality: `Ugandan`, phoneCode: `+256` },
      { isoCode: `UA`, name: `Ukraine`, nationality: `Ukrainian`, phoneCode: `+380` },
      { isoCode: `AE`, name: `United Arab Emirates`, nationality: `Emirati`, phoneCode: `+971` },
      { isoCode: `GB`, name: `United Kingdom`, nationality: `British`, phoneCode: `+44` },
      { isoCode: `US`, name: `United States`, nationality: `American`, phoneCode: `+1` },
      {
        isoCode: `UM`,
        name: `United States Minor Outlying Islands`,
        nationality: `American`,
        phoneCode: `+1`,
      },
      { isoCode: `UY`, name: `Uruguay`, nationality: `Uruguayan`, phoneCode: `+598` },
      { isoCode: `UZ`, name: `Uzbekistan`, nationality: `Uzbekistani`, phoneCode: `+998` },
      { isoCode: `VU`, name: `Vanuatu`, nationality: `Ni-Vanuatu`, phoneCode: `+678` },
      { isoCode: `VE`, name: `Venezuela`, nationality: `Venezuelan`, phoneCode: `+58` },
      { isoCode: `VN`, name: `Viet Nam`, nationality: `Vietnamese`, phoneCode: `+84` },
      {
        isoCode: `VG`,
        name: `Virgin Islands, British`,
        nationality: `British Virgin Islander`,
        phoneCode: `+1284`,
      },
      {
        isoCode: `VI`,
        name: `Virgin Islands, U.S.`,
        nationality: `U.S. Virgin Islander`,
        phoneCode: `+1340`,
      },
      {
        isoCode: `WF`,
        name: `Wallis and Futuna`,
        nationality: `Wallisian or Futunan`,
        phoneCode: `+681`,
      },
      { isoCode: `EH`, name: `Western Sahara`, nationality: `Sahrawi`, phoneCode: `+212` },
      { isoCode: `YE`, name: `Yemen`, nationality: `Yemeni`, phoneCode: `+967` },
      { isoCode: `ZM`, name: `Zambia`, nationality: `Zambian`, phoneCode: `+260` },
      { isoCode: `ZW`, name: `Zimbabwe`, nationality: `Zimbabwean`, phoneCode: `+263` },
    ])
  }
}
