import SubNavItem from '#models/sub_nav_item'
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'

export default class extends BaseSeeder {
  static environment = ['development', 'test', 'production']

  async run() {
    const uniqueKey = 'title'

    await SubNavItem.updateOrCreateMany(uniqueKey, [
      {
        navItemId: 1,
        title: 'Cause Lists',
        url: '/legal/cause-lists',
        icon: 'heroicons:document-text',
        iconSolid: 'heroicons:document-text-solid',
        listOrder: 1,
      },
      {
        navItemId: 1,
        title: 'Court Attendance Notes',
        url: '/legal/court-attendance-notes',
        icon: 'heroicons:document-duplicate',
        iconSolid: 'heroicons:document-duplicate-solid',
        listOrder: 2,
      },
      {
        navItemId: 1,
        title: 'Timesheets',
        url: '/legal/timesheets',
        icon: 'heroicons:calendar-date-range',
        iconSolid: 'heroicons:calendar-date-range-solid',
        listOrder: 3,
      },
      {
        navItemId: 1,
        title: 'Lawyer Stopwatch',
        url: '/legal/lawyer-stopwatch',
        icon: 'bi:stopwatch',
        iconSolid: 'bi:stopwatch-fill',
        listOrder: 4,
        deletedAt: DateTime.now(),
      },
      {
        navItemId: 1,
        title: 'Bring-Ups',
        url: '/legal/bring-ups',
        icon: 'heroicons:bell-alert',
        iconSolid: 'heroicons:bell-alert-solid',
        listOrder: 5,
      },
      {
        navItemId: 1,
        title: 'Projects',
        url: '/legal/projects',
        icon: 'heroicons:presentation-chart-line',
        iconSolid: 'heroicons:presentation-chart-line-solid',
        listOrder: 6,
        deletedAt: DateTime.now(),
      },
      {
        navItemId: 2,
        title: 'Deposit Request Notes',
        url: '/finance/deposit-request-notes',
        icon: 'heroicons:document-currency-euro',
        iconSolid: 'heroicons:document-currency-euro-solid',
        listOrder: 7,
      },
      {
        navItemId: 2,
        title: 'Fee Notes',
        url: '/finance/fee-notes',
        icon: 'heroicons:document-currency-dollar',
        iconSolid: 'heroicons:document-currency-dollar-solid',
        listOrder: 8,
      },
      {
        navItemId: 2,
        title: 'Credit Notes',
        url: '/finance/credit-notes',
        icon: 'heroicons:document-currency-pound',
        iconSolid: 'heroicons:document-currency-pound-solid',
        listOrder: 9,
      },
      {
        navItemId: 2,
        title: 'Receipts',
        url: '/finance/receipts',
        icon: 'heroicons:document-text',
        iconSolid: 'heroicons:document-text-solid',
        listOrder: 10,
      },
      {
        navItemId: 2,
        title: 'Purchase Orders',
        url: '/finance/purchase-orders',
        icon: 'heroicons:document-currency-yen',
        iconSolid: 'heroicons:document-currency-yen-solid',
        listOrder: 11,
      },
      {
        navItemId: 3,
        title: 'Leave Applications',
        url: '/staff/leave-applications',
        icon: 'heroicons:calendar-date-range',
        iconSolid: 'heroicons:calendar-date-range-solid',
        listOrder: 12,
      },
      {
        navItemId: 3,
        title: 'Staff Recruitments',
        url: '/staff/recruitments',
        icon: 'heroicons:user-plus',
        iconSolid: 'heroicons:user-plus-solid',
        listOrder: 13,
      },
      {
        navItemId: 3,
        title: 'Staff Particulars',
        url: '/staff/staff-particulars',
        icon: 'heroicons:user-circle',
        iconSolid: 'heroicons:user-circle-solid',
        listOrder: 14,
      },
      {
        navItemId: 3,
        title: 'Exit Checklists',
        url: '/staff/exit-checklists',
        icon: 'heroicons:user-minus',
        iconSolid: 'heroicons:user-minus-solid',
        listOrder: 15,
      },
      {
        navItemId: 3,
        title: 'Staff List',
        url: '/staff/staff-list',
        icon: 'heroicons:user-group',
        iconSolid: 'heroicons:user-group-solid',
        listOrder: 16,
      },
      {
        navItemId: 4,
        title: 'KYC Checklists',
        url: '/general/kyc-checklists',
        icon: 'heroicons:clipboard-document-list',
        iconSolid: 'heroicons:clipboard-document-list-solid',
        listOrder: 17,
      },
      {
        navItemId: 4,
        title: 'Meeting Minutes',
        url: '/general/minutes',
        icon: 'heroicons:document-text',
        iconSolid: 'heroicons:document-text-solid',
        listOrder: 18,
      },
      {
        navItemId: 4,
        title: 'Newsfeeds',
        url: '/general/newsfeeds',
        icon: 'emojione-monotone:newspaper',
        iconSolid: 'emojione-monotone:newspaper',
        listOrder: 19,
      },
      {
        navItemId: 4,
        title: 'Library',
        url: '/general/library',
        icon: 'fluent:library-24-regular',
        iconSolid: 'fluent:library-24-filled',
        listOrder: 20,
      },
      {
        navItemId: 4,
        title: 'Events',
        url: '/general/events',
        icon: 'heroicons:calendar-days',
        iconSolid: 'heroicons:calendar-days-solid',
        listOrder: 21,
        deletedAt: DateTime.now(),
      },
      {
        navItemId: 4,
        title: 'Allocation Register',
        url: '/general/allocation-register',
        icon: 'material-symbols:menu-book-outline-rounded',
        iconSolid: 'material-symbols:menu-book-rounded',
        deletedAt: DateTime.now(),
      },
      {
        navItemId: 4,
        title: 'Matter Submissions',
        url: '/general/matter-submissions',
        icon: 'heroicons:clipboard-document',
        iconSolid: 'heroicons:clipboard-document-solid',
        listOrder: 23,
        deletedAt: DateTime.now(),
      },
      {
        navItemId: 4,
        title: 'Event Briefs',
        url: '/general/event-briefs',
        icon: 'heroicons:calendar-date-range',
        iconSolid: 'heroicons:calendar-date-range-solid',
        listOrder: 24,
      },
      {
        navItemId: 5,
        title: 'Bank Accounts',
        url: '/settings/bank-accounts',
        icon: 'heroicons:building-library',
        iconSolid: 'heroicons:building-library-solid',
        listOrder: 25,
      },
      {
        navItemId: 5,
        title: 'Exchange Rates',
        url: '/settings/exchange-rates',
        icon: 'heroicons:presentation-chart-line',
        iconSolid: 'heroicons:presentation-chart-line-solid',
        listOrder: 26,
      },
      {
        navItemId: 5,
        title: 'Matters',
        url: '/general/matters',
        icon: 'heroicons:clipboard-document-list',
        iconSolid: 'heroicons:clipboard-document-list-solid',
        listOrder: 27,
      },
      {
        navItemId: 5,
        title: 'Clients',
        url: '/settings/clients',
        icon: 'heroicons:user-group',
        iconSolid: 'heroicons:user-group-solid',
        listOrder: 28,
      },
      {
        navItemId: 5,
        title: 'Vendors',
        url: '/settings/vendors',
        icon: 'heroicons:users',
        iconSolid: 'heroicons:users-solid',
        listOrder: 29,
      },
      {
        navItemId: 5,
        title: 'System Permissions',
        url: '/settings/system-permissions',
        icon: 'heroicons:adjustments-horizontal',
        iconSolid: 'heroicons:adjustments-horizontal-solid',
        listOrder: 30,
      },
      {
        navItemId: 5,
        title: 'Aderant Employees',
        url: '/settings/aderant-employees',
        icon: 'heroicons:user-circle',
        iconSolid: 'heroicons:user-circle-solid',
        listOrder: 30,
      },
    ])
  }
}
